-- MySQL Script generated by MySQL Workbench
-- 05/14/17 11:50:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProjetoM3DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProjetoM3DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetoM3DB` DEFAULT CHARACTER SET utf8 ;
USE `ProjetoM3DB` ;

-- -----------------------------------------------------
-- Table `ProjetoM3DB`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoM3DB`.`disciplina` (
  `IdDisciplina` INT NOT NULL AUTO_INCREMENT,
  `NomeDisciplina` VARCHAR(45) NULL,
  `CargaHoraria` INT NULL,
  `Curso` VARCHAR(45) NULL,
  `NumeroVagas` INT NULL,
  `Periodo` VARCHAR(45) NULL,
  PRIMARY KEY (`IdDisciplina`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
